FROM beeline-firmware-img:latest
LABEL author="Mark Uckermann <mark.uckermann@gmail.com>"

RUN apt-get install -y gdb

#requires beeline-firmware-img to exist on local system
#build it with 'docker build -t beeline-firmware-img beeline-firmware-build